    const bountyData = [
        { id: "aphra", name: "Doctor Aphra", role: "Employer", desc: "Rogue Archaeologist. Constantly looking for 'independent contractors' to uncover dangerous Sith artifacts.", location: "Unknown Outer Rim", reward: "2,000 cr + Artifacts", defaultStatus: "Active" },
        { id: "dash", name: "Dash Rendar", role: "Rival", desc: "Cocky smuggler flying the Outrider. Often beats you to the best transport jobs.", location: "Corellian Sector", reward: "None (Rivalry)", defaultStatus: "Active" },
        { id: "xizor", name: "Prince Xizor", role: "Employer/Target", desc: "Falleen leader of the Black Sun syndicate. Extremely dangerous to cross.", location: "Coruscant", reward: "50,000 cr", defaultStatus: "Active" },
        { id: "cadbane", name: "Cad Bane", role: "Target", desc: "Legendary Duros bounty hunter. High priority target for the New Republic.", location: "Tatooine", reward: "25,000 cr", defaultStatus: "Active" },
        { id: "ig88", name: "IG-88", role: "Rival", desc: "Rogue assassin droid. Completely ruthless and lacks any organic empathy.", location: "Bounty Hunters Guild", reward: "15,000 cr", defaultStatus: "Active" },
        { id: "bossk", name: "Bossk", role: "Rival", desc: "Trandoshan hunter who specializes in capturing Wookiees.", location: "Kashyyyk Orbit", reward: "10,000 cr", defaultStatus: "Active" },
        { id: "mohc", name: "General Rom Mohc", role: "Target", desc: "Imperial officer behind the Dark Trooper project. High value Rebel target.", location: "Arc Hammer", reward: "100,000 cr", defaultStatus: "Active" },
        { id: "mara", name: "Mara Jade", role: "Target", desc: "The Emperor's Hand. Force-sensitive operative hunting remaining Jedi and Rebel leaders.", location: "Classified", reward: "Unknown", defaultStatus: "Active" }
    ];

    function canLearnPower(spell, character) {
        if (!character.cls || character.cls === 'None') return false;
        const code = classCodeMap[character.cls];
        if (!code) return false;
        
        // Cantrips are level 0
        const spellLvl = lvlOrder[spell.lvl] || 0;
        const maxLvl = maxSpellLevel(character.cls, parseInt(character.level) || 1);
        
        const isClassMatch = spell.classes.includes(code);
        const isLevelMatch = spellLvl <= maxLvl;
        
        return {
            allowed: isClassMatch && isLevelMatch,
            reason: !isClassMatch ? `Class Mismatch (${character.cls})` : (!isLevelMatch ? `Level Too Low (Max: ${maxLvl})` : null)
        };
    }

    // --- COMPREHENSIVE DATABASES ---
    const classMilestones = {
        "None": ["Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian", "Civilian"],
        "Fighter": ["Recruit", "Grunt", "Trooper", "Veteran", "Commando", "Sergeant", "Lieutenant", "Captain", "Major", "Vanguard", "Commander", "Colonel", "General", "Elite Commando", "Champion", "Warlord", "Hero of the Rebellion", "Supreme Commander", "Mythic Warrior", "Galactic Legend"],
        "Rogue": ["Streetrat", "Pickpocket", "Smuggler", "Scoundrel", "Operative", "Slicer", "Infiltrator", "Shadow", "Agent", "Fixer", "Master Slicer", "Assassin", "Ghost", "Syndicate Boss", "Phantom", "Mastermind", "Shadow Broker", "Mythic Scoundrel", "Unseen Legend", "Galactic Ghost"],
        "Paladin": ["Force Sensitive", "Initiate", "Padawan", "Jedi Knight", "Jedi Guardian", "Peacekeeper", "Jedi Commander", "Jedi General", "Master Guardian", "Jedi Master", "Lightbringer", "Force Champion", "Council Member", "Grandmaster", "Sword of the Jedi", "Force Avatar", "Living Force", "Mythic Knight", "Legend of the Order", "Galactic Savior"],
        "Sorcerer": ["Force Sensitive", "Acolyte", "Adept", "Mystic", "Sith Inquisitor", "Dark Acolyte", "Dark Jedi", "Sith Warrior", "Sith Lord", "Master Mystic", "Force Weaver", "Dark Council", "Darth", "Force Avatar", "Sith Master", "Emperor's Hand", "Dark Lord of the Sith", "Mythic Sorcerer", "Living Dark Side", "Galactic Terror"],
        "Monk": ["Trainee", "Martial Artist", "Teräs Käsi Novice", "Jedi Sentinel", "Shadow Guard", "Teräs Käsi Adept", "Warrior Monk", "Temple Guard", "Master Sentinel", "Teräs Käsi Master", "Force Hand", "Grand Inquisitor", "Blind Master", "Grand Sentinel", "Living Weapon", "Force Martial Master", "Mythic Monk", "Grandmaster of the Hand", "Legendary Sentinel", "Galactic Ascendant"],
        "Ranger": ["Tracker", "Scout", "Hunter", "Bounty Hunter", "Mandalorian Foundling", "Pathfinder", "Stalker", "Sniper", "Mandalorian Warrior", "Apex Hunter", "Master Tracker", "Bounty Master", "Mandalorian Captain", "Predator", "Beastmaster", "Mandalorian Commander", "Mythic Hunter", "Mand'alor", "Legendary Tracker", "Galactic Apex"],
        "Artificer": ["Tinkerer", "Mechanic", "Droidsmith", "Engineer", "Tech Specialist", "Master Slicer", "Chief Engineer", "Innovator", "Master Mechanic", "Tech Lord", "Cyberneticist", "Master Droidsmith", "Architect", "Genius", "Tech Savant", "Master Architect", "Mythic Inventor", "Legendary Engineer", "Galactic Creator", "Machine God"],
        "Cleric": ["Devotee", "Acolyte", "Force Priest", "Healer", "High Priest", "Seer", "Oracle", "Prelate", "Bishop", "Arch-Prelate", "Force Conduit", "Prophet", "High Seer", "Chosen", "Voice of the Force", "Divine Avatar", "Living Saint", "Mythic Priest", "Legendary Oracle", "Galactic Savior"],
        "Wizard": ["Initiate", "Apprentice", "Force Scholar", "Researcher", "Arcanist", "Mage", "Lorekeeper", "Sage", "High Mage", "Archmage", "Holocron Keeper", "Master Scholar", "Grand Sage", "Archivist", "Master of Lore", "Force Weaver", "Grandmaster", "Mythic Scholar", "Legendary Mage", "Galactic Oracle"],
        "Bard": ["Operative", "Entertainer", "Diplomat", "Envoy", "Senatorial Aide", "Spy", "Ambassador", "Master Spy", "Minister", "High Envoy", "Master Diplomat", "Chancellor", "Senator", "Grand Minister", "Supreme Chancellor", "Voice of the People", "Galactic Icon", "Mythic Diplomat", "Legendary Envoy", "Galactic Leader"],
        "Warlock": ["Aspirant", "Cultist", "Dark Apprentice", "Adept", "Inquisitor", "Dark Seeker", "Shadow Adept", "Dark Master", "High Inquisitor", "Sith Lord", "Grand Inquisitor", "Dark Prophet", "Shadow Lord", "Harbinger", "Master of Shadows", "Avatar of the Dark", "Sith Master", "Mythic Warlock", "Legendary Cultist", "Galactic Terror"],
        "Druid": ["Seeker", "Wanderer", "Living-Force Mystic", "Shaman", "Beastmaster", "Force Guide", "Earthcaller", "Nature Walker", "Master Shaman", "Force Seer", "High Mystic", "Spirit Guide", "Archdruid", "Force Avatar", "Master of the Wild", "Living Force", "One With the Force", "Mythic Shaman", "Legendary Mystic", "Galactic Warden"]
    };

    const classData = [
        { dnd: "Fighter", sw: "Mandalorian / Rebel Commando", hitDie: "1d10", primary: "Strength or Dexterity", saves: "Strength, Constitution", desc: "The masters of weaponry. Focus on Ranged for blasters, or Melee for Vibro-weapons.", features: "Second Wind (Bacta Injector), Action Surge (Overdrive).", fullDesc: "Whether clad in Mandalorian iron or standard-issue Rebel fatigues, Fighters are the tactical backbone of any squad. They rely on heavy armor, mastery of martial weapons, and pure grit.\n\n<b>Translation Notes:</b>\n• <b>Second Wind:</b> Flavored as an emergency auto-injector of Bacta built into your armor.\n• <b>Action Surge:</b> A burst of pure combat adrenaline, pushing your reflexes beyond normal limits for a few vital seconds.\n• <b>Archery Style:</b> Highly recommended for Blaster Rifle users, granting a flat +2 to attack rolls." },
        { dnd: "Rogue", sw: "Scoundrel / Slicer", hitDie: "1d8", primary: "Dexterity", saves: "Dexterity, Intelligence", desc: "Smugglers and spies. Sneak Attack represents hitting weak points in armor.", features: "Sneak Attack (Precision Shot), Cunning Action (Tactical Retreat).", fullDesc: "Surviving the Outer Rim requires quick wits and a quicker blaster hand. Rogues represent the smugglers, bounty hunters, and slicers who fight dirty and strike from the shadows.\n\n<b>Translation Notes:</b>\n• <b>Sneak Attack:</b> Finding the microscopic gap in stormtrooper plating, or shooting a distracted enemy in the back. Requires a finesse weapon (Vibro-shiv) or ranged weapon (Blaster).\n• <b>Cunning Action:</b> Using a bonus action to dive behind cargo crates (Hide/Dash) or duck out of melee (Disengage).\n• <b>Thieves' Tools:</b> Replaced entirely by a Slicer Kit used for hacking doors and terminals." },
        { dnd: "Paladin", sw: "Jedi Guardian", hitDie: "1d10", primary: "Strength & Charisma", saves: "Wisdom, Charisma", desc: "The heavy-hitting, armored Jedi. Divine Smite is channeling the Force into your strikes.", features: "Divine Smite (Force Strike), Lay on Hands (Force Mend).", fullDesc: "Jedi Guardians are the frontline warriors of the Order, often wearing partial armor over their robes. They rely on physical prowess augmented by the Force.\n\n<b>Translation Notes:</b>\n• <b>Divine Smite:</b> Channeling raw Force energy directly into your lightsaber or vibrosword, causing it to flare violently and melt through armor. (Radiant damage translates perfectly as pure plasma/energy).\n• <b>Lay on Hands:</b> Using the Light Side of the Force to knit wounds together through physical touch." },
        { dnd: "Sorcerer", sw: "Force Adept / Sith Inquisitor", hitDie: "1d6", primary: "Charisma", saves: "Constitution, Charisma", desc: "Raw, innate connection to the Force. Metamagic allows you to bend the rules.", features: "Font of Magic (Force Reserves), Metamagic (Force Manipulation).", fullDesc: "Unlike heavily trained Jedi, Sorcerers represent those with an explosive, innate, and often untamed connection to the Force. They rely on Charisma (force of will) to manifest their powers.\n\n<b>Translation Notes:</b>\n• <b>Sorcery Points:</b> Represent your raw stamina in the Force. Burning yourself out to cast more powers.\n• <b>Metamagic:</b> The true power of an Adept. <i>Twinned Spell</i> allows you to Force Choke two targets at once. <i>Subtle Spell</i> allows you to use Mind Tricks without waving your hand or speaking." },
        { dnd: "Monk", sw: "Jedi Sentinel / Martial Artist", hitDie: "1d8", primary: "Dexterity & Wisdom", saves: "Strength, Dexterity", desc: "Unarmored, agile fighters. Deflect Missiles perfectly translates to batting away blaster bolts.", features: "Martial Arts (Teräs Käsi), Ki Points (Force Focus), Deflect Missiles.", fullDesc: "Monks are the cinematic translation of unarmored, highly agile Jedi or masters of Teräs Käsi. They dart across the battlefield, striking with a flurry of blows.\n\n<b>Translation Notes:</b>\n• <b>Ki Points:</b> A deep, meditational focus in the living Force, used to enhance speed and strikes.\n• <b>Deflect Missiles:</b> This is the ultimate Jedi mechanic. When shot by a blaster, use your reaction to reduce the damage. If you reduce it to 0, you use your lightsaber to reflect the blaster bolt right back at the attacker!" },
        { dnd: "Ranger", sw: "Bounty Hunter / Scout", hitDie: "1d10", primary: "Dexterity & Wisdom", saves: "Strength, Dexterity", desc: "Trackers of the Outer Rim. Hunter's Mark is a tracking fob or HUD lock-on.", features: "Favored Enemy (Bounty Targets), Hunter's Mark (Target Lock).", fullDesc: "Rangers are the ultimate survivalists and bounty hunters. They excel in tracking specific prey across the galaxy and using specialized gear to gain the upper hand in the wild.\n\n<b>Translation Notes:</b>\n• <b>Hunter's Mark:</b> Activating a thermal tracking lock in your helmet's HUD, or planting a microscopic tracker on your target to deal extra damage on every hit.\n• <b>Spells:</b> Ranger 'magic' should be flavored entirely as tech. <i>Ensnaring Strike</i> is an electrified net gun. <i>Pass without Trace</i> is a camouflage poncho." },
        { dnd: "Artificer", sw: "Droidsmith / Engineer", hitDie: "1d8", primary: "Intelligence", saves: "Constitution, Intelligence", desc: "Tech wizards. Spells are deployed as mini-droids, wrist-mounted flamethrowers.", features: "Magical Tinkering (Tech Jury-Rigging), Infuse Item (Weapon Mods).", fullDesc: "Artificers keep the rust-bucket ships flying and the blasters firing. They are masters of technology, droids, and on-the-fly modifications.\n\n<b>Translation Notes:</b>\n• <b>Spells:</b> Like the Ranger, all Artificer magic is technology. <i>Cure Wounds</i> is a deployed medical astromech. <i>Fire Bolt</i> is a wrist-mounted miniature rocket.\n• <b>Infuse Item:</b> Modifying the party's gear. Adding a heavy magnetic coil to a Vibrosword (Enhanced Weapon)." },
        { dnd: "Cleric", sw: "Force Priest / Order Devotee", hitDie: "1d8", primary: "Wisdom", saves: "Wisdom, Charisma", desc: "Channels devotion to the Force or an ancient creed. Master healers and buffers.", features: "Channel Divinity (Force Conviction), Turn Undead (Banish Dark Spirits).", fullDesc: "Clerics represent those deeply devoted to the spiritual side of the Force, such as the Church of the Force or ancient Sith cults.\n\n<b>Translation Notes:</b>\n• <b>Healing:</b> Powerful Light Side mending.\n• <b>Channel Divinity:</b> Calling upon the deepest reserves of your faith to turn the tide of battle." },
        { dnd: "Wizard", sw: "Sith Sorcerer / Force Scholar", hitDie: "1d6", primary: "Intelligence", saves: "Intelligence, Wisdom", desc: "Studied user of the Force. Spellbook is a holocron filled with cataloged techniques.", features: "Spellbook (Personal Holocron), Arcane Recovery (Meditation).", fullDesc: "Wizards are the scholars. Unlike Sorcerers who rely on instinct, Wizards study ancient Holocrons to master complex Force techniques.\n\n<b>Translation Notes:</b>\n• <b>Spellbook:</b> A physical Holocron or datapad containing your accumulated knowledge.\n• <b>Ritual Casting:</b> Taking ten minutes to perform a complex Sith alchemy ritual or deep Jedi meditation." },
        { dnd: "Bard", sw: "Diplomat / Spy", hitDie: "1d8", primary: "Charisma", saves: "Dexterity, Charisma", desc: "Words and presence. Bardic Inspiration is rallying squad-level morale.", features: "Bardic Inspiration (Tactical Comms), Cutting Words (Disrupt Concentration).", fullDesc: "Bards are the face of the party. Senators, diplomats, or high-end spies who use their presence (and subtle Force manipulation) to control the battlefield.\n\n<b>Translation Notes:</b>\n• <b>Bardic Inspiration:</b> Shouting tactical commands over the commlink or inspiring your allies with a rousing speech.\n• <b>Spells:</b> A mix of mind tricks, sonic weapons, and tactical buffs." },
        { dnd: "Warlock", sw: "Dark Side Apprentice / Cult Adept", hitDie: "1d8", primary: "Charisma", saves: "Wisdom, Charisma", desc: "Bound to a powerful patron — an ancient Sith spirit, a Bendu, or an Inquisitor.", features: "Eldritch Blast (Focused Push), Pact Boon (Patron's Gift).", fullDesc: "Warlocks have made a pact with a higher power for quick, destructive abilities. Their magic is aggressive and recharges quickly.\n\n<b>Translation Notes:</b>\n• <b>Pact Magic:</b> You draw power directly from your master. It recharges on a short rest because you are channeling their energy, not your own.\n• <b>Invocations:</b> Permanent, passive mutations or specialized dark side training granted by your patron." },
        { dnd: "Druid", sw: "Living Force Mystic", hitDie: "1d8", primary: "Wisdom", saves: "Intelligence, Wisdom", desc: "Communes with the Living Force. Wild Shape is deep meditative bonding with creatures.", features: "Wild Shape (Beast Bond), Speak with Animals (Force Empathy).", fullDesc: "Druids connect with the flora and fauna of the galaxy. They are the mystics living in exile on Dagobah or Lothal.\n\n<b>Translation Notes:</b>\n• <b>Wild Shape:</b> Instead of physically transforming, you can flavor this as forming a profound psychic bond with a local beast, controlling it while your real body meditates.\n• <b>Spells:</b> Manipulating the environment, causing vines to grasp enemies, or calling down lightning storms." }
    ];

    const speciesData = [
        { dnd: "Human", sw: "Human / Clone", desc: "The most common and adaptable species in the galaxy. Found everywhere from Coruscant to the Outer Rim.", features: "Versatile, adaptable, extra skill/feat.", stats: "+1 to all Ability Scores OR +2 to one and +1 to another. Speed 30 ft." },
        { dnd: "Elf (High/Wood)", sw: "Twi'lek / Togruta", desc: "Graceful and deeply attuned to the natural flow of the galaxy. Often highly agile and perceptive.", features: "Keen Senses, Trance, innate grace.", stats: "+2 Dexterity, +1 to another stat. Speed 30 ft (or 35 ft). Darkvision 60 ft." },
        { dnd: "Dwarf", sw: "Wookiee / Gamorrean", desc: "Incredibly tough, strong, and deeply loyal to their clans. Known for their physical resilience and crafting.", features: "Resilience, combat training.", stats: "+2 Constitution. Speed 25 ft. Darkvision 60 ft. Advantage on saving throws against poison." },
        { dnd: "Halfling", sw: "Rodian / Ewok", desc: "Small, nimble, and surprisingly lucky. Often underestimated by larger species.", features: "Lucky, Nimble, Brave.", stats: "+2 Dexterity. Speed 25 ft. Reroll 1s on d20s. Advantage against being frightened." },
        { dnd: "Gnome", sw: "Jawa / Chadra-Fan / Ugnaught", desc: "Small, highly intelligent scavengers and tinkerers. Known for their technological intuition and survival skills.", features: "Scavenger, Tinker, Darkvision.", stats: "+2 Intelligence. Speed 25 ft. Darkvision 60 ft. Advantage on Int/Wis/Cha saves vs magic." },
        { dnd: "Dragonborn", sw: "Trandoshan / Noghri", desc: "Large, imposing reptilian or warrior species. Known for their physical power and natural weapons.", features: "Breath Weapon, Resistance.", stats: "+2 Strength, +1 Charisma. Speed 30 ft. Breath Weapon deals 2d6 damage. Damage Resistance." },
        { dnd: "Tiefling", sw: "Sith Pureblood / Devaronian", desc: "Carrying a dark legacy, they possess an innate connection to dark side magics and fire.", features: "Darkvision, Hellish Resistance, Innate Spells.", stats: "+2 Charisma, +1 Intelligence. Speed 30 ft. Darkvision 60 ft. Fire Resistance." },
        { dnd: "Half-Orc", sw: "Lasat / Besalisk", desc: "Fierce, towering warriors known for their incredible endurance in battle.", features: "Relentless Endurance, Savage Attacks.", stats: "+2 Strength, +1 Constitution. Speed 30 ft. Drops to 1 HP instead of 0 once per day." },
        { dnd: "Half-Elf", sw: "Pantoran / Mirialan", desc: "Charismatic and adaptable, often serving as diplomats or high-ranking operatives.", features: "Skill Versatility, Fey Ancestry.", stats: "+2 Charisma, +1 to two other stats. Speed 30 ft. Darkvision 60 ft. Advantage against being charmed." }
    ];

    const armoryData = [
        { cat: "Melee", dnd: "Dagger", sw: "Vibro-dagger", dmg: "1d4 Piercing", props: "Finesse, Light, Thrown (20/60)", weight: "1 lb", cost: "50 cr", desc: "A short, concealable vibrating blade.", fullDesc: "A standard vibro-dagger. Highly concealable and lethal in close quarters. Often carried as a hold-out weapon by spacers and bounty hunters." },
        { cat: "Melee", dnd: "Shortsword", sw: "Vibro-shiv", dmg: "1d6 Piercing", props: "Finesse, Light", weight: "2 lb", cost: "100 cr", desc: "Finesse. Standard smuggler backup weapon. Easily concealed.", fullDesc: "A short, brutal blade equipped with an ultrasonic vibration generator in the hilt. The high-frequency vibrations allow it to slice through flesh and light armor with terrifying ease. Highly favored by street thugs, assassins, and smugglers." },
        { cat: "Melee", dnd: "Longsword", sw: "Vibrosword", dmg: "1d8 Slashing", props: "Versatile (1d10)", weight: "3 lb", cost: "150 cr", desc: "High-frequency vibrating edge cuts through plasteel. The standard mercenary blade.", fullDesc: "The staple weapon of mercenaries across the galaxy. The vibrosword features a long, straight durasteel blade that vibrates at incredibly high frequencies. It can be wielded with one or two hands." },
        { cat: "Melee", dnd: "Greatsword", sw: "Heavy Vibro-blade", dmg: "2d6 Slashing", props: "Heavy, Two-Handed", weight: "6 lb", cost: "300 cr", desc: "A massive, two-handed vibrating sword.", fullDesc: "A massive vibro-weapon requiring two hands to wield effectively. The sheer kinetic force of the vibrating blade can sheer through light vehicle armor and blast doors." },
        { cat: "Melee", dnd: "Rapier", sw: "Electrostaff", dmg: "1d8 Piercing/Bludgeon", props: "Finesse", weight: "2 lb", cost: "250 cr", desc: "Finesse. Energy-arcing tips, famously used by MagnaGuards.", fullDesc: "A long, balanced staff made of phrik or cortosis alloy, rendering it resistant to lightsaber strikes. Both ends of the staff project lethal electromagnetic energy. Wielded with elegant, precise strikes." },
        { cat: "Melee", dnd: "Glaive / Halberd", sw: "Force Pike", dmg: "1d10 Slashing", props: "Heavy, Reach, Two-Handed", weight: "6 lb", cost: "400 cr", desc: "Long-reach polearm with a vibrating/electrified tip.", fullDesc: "Standard issue for Emperor's Royal Guards and elite planetary security. Features a long shaft granting extended reach, tipped with a highly lethal vibro-edged or electrified head." },
        { cat: "Melee", dnd: "Maul", sw: "Heavy Shock Maul", dmg: "2d6 Bludgeoning", props: "Heavy, Two-Handed", weight: "10 lb", cost: "200 cr", desc: "Heavy, Two-Handed. Brutal kinetic impact combined with localized EMP bursts.", fullDesc: "A massive, brutal bludgeoning weapon. Upon impact, the heavy head of the maul discharges a violent shock of kinetic and electrical energy. Exceptionally heavy but devastating against armored droids." },
        { cat: "Melee", dnd: "Whip", sw: "Neuronic Whip", dmg: "1d4 Slashing", props: "Finesse, Reach", weight: "3 lb", cost: "150 cr", desc: "A flexible, electrified whip used by slavers.", fullDesc: "A cruel weapon that delivers a paralyzing neural shock upon striking bare flesh. It possesses incredible reach and can wrap around limbs or weapons." },
        { cat: "Melee", dnd: "Sun Blade", sw: "Training Lightsaber", dmg: "1d8 Radiant", props: "Finesse, Versatile", weight: "1 lb", cost: "500 cr", desc: "Low-power plasma blade. Sears but rarely amputates.", fullDesc: "A lightsaber whose emitter matrix has been dialed back significantly. It causes searing burns rather than amputation, rendering it safer for Padawans. Still deals radiant (plasma) damage, but lacks the pure cutting power of a true weapon." },
        { cat: "Melee", dnd: "Vorpal Sword", sw: "True Lightsaber", dmg: "2d8 Radiant", props: "Finesse, Deadly", weight: "1 lb", cost: "Priceless", desc: "The iconic death-dealing machine. Severs limbs on a critical hit.", fullDesc: "A fully weaponized plasma blade powered by a pristine Kyber crystal. It ignores non-magical resistance to slashing damage. On a critical hit (rolling a 20), the immense heat instantly cauterizes as it completely severs one of the target's limbs, or instantly destroys non-boss droids." },
        
        { cat: "Ranged", dnd: "Dart", sw: "Throwing Knives", dmg: "1d4 Piercing", props: "Finesse, Thrown (20/60)", weight: "0.25 lb", cost: "5 cr", desc: "Balanced blades for throwing.", fullDesc: "Perfectly balanced throwing knives, often magnetically sealed to stick to armor. A favorite of stealth operatives." },
        { cat: "Ranged", dnd: "Hand Crossbow", sw: "Hold-out Blaster", dmg: "1d6 Energy", props: "Ammunition (30/120), Light", weight: "3 lb", cost: "75 cr", desc: "Range 30/120. Concealable, perfect for dual-wielding Scoundrels.", fullDesc: "A miniature blaster pistol designed for concealment. It packs less of a punch than standard military gear but can be fired rapidly with one hand. Ideal for 'shooting first'." },
        { cat: "Ranged", dnd: "Shortbow", sw: "Blaster Pistol", dmg: "1d6 Energy", props: "Ammunition (80/320), Two-Handed", weight: "2 lb", cost: "250 cr", desc: "Range 80/320. Reliable sidearm. Standard issue for Rebel officers.", fullDesc: "The ubiquitous DL-44 or similar standard blaster pistol. Highly reliable, easy to maintain, and effective at medium range. The standard sidearm for officers and smugglers." },
        { cat: "Ranged", dnd: "Light Crossbow", sw: "Blaster Carbine", dmg: "1d8 Energy", props: "Ammunition (80/320), Two-Handed", weight: "5 lb", cost: "500 cr", desc: "Range 80/320. Compact, rapid-fire military rifle used by Stormtroopers.", fullDesc: "A compact version of a heavy blaster rifle, sacrificing extreme range for mobility. The E-11 carbine is the standard issue for Imperial Stormtroopers." },
        { cat: "Ranged", dnd: "Longbow", sw: "Heavy Blaster Rifle", dmg: "1d8 Energy", props: "Ammunition (150/600), Heavy, Two-Handed", weight: "2 lb", cost: "500 cr", desc: "Range 150/600. Heavy, powerful, requires two hands. Used by snipers.", fullDesc: "A long-barreled blaster rifle designed for extreme range and precision. It fires a highly concentrated bolt of plasma. Due to its length and recoil, it requires two hands." },
        { cat: "Ranged", dnd: "Heavy Crossbow", sw: "Bowcaster", dmg: "1d10 Energy", props: "Ammunition (100/400), Heavy, Loading", weight: "18 lb", cost: "800 cr", desc: "Range 100/400. Heavy, Loading. Wookiee weapon firing magnetic quarrels.", fullDesc: "A traditional Wookiee weapon that uses magnetic acceleration to fire explosive quarrels wrapped in plasma energy. Incredibly heavy and possesses massive recoil." },
        { cat: "Ranged", dnd: "", sw: "Ion Blaster", dmg: "1d8 Lightning", props: "Ammunition (80/320)", weight: "3 lb", cost: "400 cr", desc: "Fires localized EMP blasts. Highly effective against Droids.", fullDesc: "A specialized blaster that fires ionized particles instead of standard plasma. It deals lightning damage. If the target is a Droid or Construct, it must succeed on a DC 13 Constitution save or suffer disadvantage on its next attack." },
        { cat: "Ranged", dnd: "", sw: "Disruptor Rifle", dmg: "1d12 Necrotic", props: "Ammunition (150/600), Heavy, Loading", weight: "10 lb", cost: "3,000 cr", desc: "Illegal, highly lethal weapon that disintegrates matter.", fullDesc: "A universally banned weapon that tears matter apart at the molecular level. It ignores temporary hit points. If a creature is reduced to 0 hit points by this weapon, it is completely disintegrated." },
        { cat: "Ranged", dnd: "", sw: "Light Repeating Blaster", dmg: "1d8 Energy", props: "Ammunition (80/320), Heavy, Two-Handed", weight: "15 lb", cost: "1,200 cr", desc: "Suppression weapon with an incredible rate of fire.", fullDesc: "A squad automatic weapon. As an action, you can target a 10-foot cube within normal range. Each creature in the area must succeed on a DC 13 Dexterity saving throw or take standard weapon damage." },

        { cat: "Explosives", dnd: "Javelin", sw: "Frag Grenade", dmg: "1d6 Piercing", props: "Thrown (30/120)", weight: "1 lb", cost: "50 cr", desc: "Thrown 30/120. Standard anti-personnel shrapnel charge.", fullDesc: "A standard military fragmentation grenade. You can throw it at a target, treating it as a ranged weapon attack. Upon impact, it detonates into lethal shrapnel." },
        { cat: "Explosives", dnd: "Alchemist's Fire", sw: "Incendiary Charge", dmg: "1d4 Fire/turn", props: "Thrown (20)", weight: "1 lb", cost: "500 cr", desc: "Covers target in burning chemical gel. Requires an action to extinguish.", fullDesc: "A flask containing a highly volatile chemical gel that ignites upon exposure to air. On a hit, the target takes 1d4 fire damage at the start of each of its turns until extinguished." },
        { cat: "Explosives", dnd: "Holy Water", sw: "Ion Grenade", dmg: "2d6 Radiant", props: "Thrown (20)", weight: "1 lb", cost: "250 cr", desc: "Specifically designed to scramble circuitry and overload droid combat frames.", fullDesc: "An explosive charge that releases a massive pulse of ionic energy rather than shrapnel. If the target is a Droid, it takes 2d6 radiant (ionic) damage. Harmless to organics." },
        { cat: "Explosives", dnd: "", sw: "Thermal Detonator", dmg: "3d6 Fire/Force", props: "Thrown (20/60)", weight: "1 lb", cost: "1,500 cr", desc: "Military-grade thermobaric explosive.", fullDesc: "A highly restricted explosive that triggers a localized fusion reaction. Destroys anything in a 10-foot radius. High chance of disintegrating cover. Each creature in radius must make a DC 13 Dex save." },
        { cat: "Explosives", dnd: "Poison Gas (Basic)", sw: "Dioxis Grenade", dmg: "1d4 Poison/turn", props: "Thrown (30/90)", weight: "1 lb", cost: "400 cr", desc: "Releases a 15-foot cloud of highly toxic green gas.", fullDesc: "Releases a dense, green toxic gas in a 15-foot radius. The area is heavily obscured. Any breathing creature that starts its turn in the cloud takes 1d4 poison damage and must make a DC 12 Con save or be Poisoned." },
        { cat: "Explosives", dnd: "", sw: "Stun Grenade (Flashbang)", dmg: "Status Effect", props: "Thrown (30/90)", weight: "1 lb", cost: "300 cr", desc: "Non-lethal sonic and photic overload.", fullDesc: "Detonates with blinding light and deafening sound in a 10-foot radius. Creatures in the area must succeed on a DC 13 Constitution save or be Blinded and Deafened until the end of their next turn." },

        { cat: "Armor", dnd: "Padded", sw: "Blast Vest", dmg: "11 + Dex", props: "Light Armor, Disadv. Stealth", weight: "8 lb", cost: "50 cr", desc: "Cheap, bulky padding worn over civilian clothes.", fullDesc: "A heavy, insulated vest providing minimal protection against shrapnel and glancing blaster shots. Its bulk makes it hard to move silently." },
        { cat: "Armor", dnd: "Leather", sw: "Smuggler Jacket", dmg: "11 + Dex", props: "Light Armor", weight: "10 lb", cost: "100 cr", desc: "Thick, blast-resistant fabrics favored in the Outer Rim.", fullDesc: "A classic spacer's jacket tailored from thick, blast-resistant synthetic fabrics. It provides minimal protection but allows for complete freedom of movement." },
        { cat: "Armor", dnd: "Studded Leather", sw: "Combat Weave", dmg: "12 + Dex", props: "Light Armor", weight: "13 lb", cost: "450 cr", desc: "Reinforced synthetic weave with micro-plating.", fullDesc: "Flexible armor featuring tiny micro-plates of durasteel sewn directly into a mesh bodysuit. Offers superior light protection for agile fighters." },
        { cat: "Armor", dnd: "Chain Shirt", sw: "Armored Flight Suit", dmg: "13 + Dex (Max 2)", props: "Medium Armor", weight: "20 lb", cost: "500 cr", desc: "Standard pilot gear with integrated impact plates.", fullDesc: "A pressurized flight suit reinforced with impact-dispersing gel and plasteel plates across the vital organs. Standard issue for starfighter squadrons." },
        { cat: "Armor", dnd: "Breastplate", sw: "Trooper Plasteel", dmg: "14 + Dex (Max 2)", props: "Medium Armor", weight: "20 lb", cost: "4,000 cr", desc: "Heavy chest piece allowing for unhindered tactical movement.", fullDesc: "A molded plasteel chest plate worn over a flexible body glove. This is the core component of standard military armor. Offers high protection for vital organs." },
        { cat: "Armor", dnd: "Half Plate", sw: "Assault Armor", dmg: "15 + Dex (Max 2)", props: "Medium Armor, Disadv. Stealth", weight: "40 lb", cost: "7,500 cr", desc: "Heavy plating protecting the torso, joints, and shins.", fullDesc: "Used by heavy infantry and shock troopers. Interlocking plasteel plates cover the majority of the body, restricting movement but offering excellent medium-tier defense." },
        { cat: "Armor", dnd: "Splint", sw: "Heavy Plasteel", dmg: "17 AC", props: "Heavy Armor, Disadv. Stealth", weight: "60 lb", cost: "2,000 cr", desc: "Bulky, overlapping strips of durasteel.", fullDesc: "An older, bulkier style of heavy armor. Overlapping strips of heavy metal are riveted to a heavy undersuit. Exceptionally noisy and heavy, but highly protective." },
        { cat: "Armor", dnd: "Plate", sw: "Heavy Mandalorian Beskar", dmg: "18 AC", props: "Heavy Armor, Disadv. Stealth", weight: "65 lb", cost: "15,000 cr", desc: "Full environmental seal, heavy plating. Disadvantage on Stealth.", fullDesc: "The pinnacle of personal defense. Interlocking plates of heavy durasteel or rare Beskar cover the entire body. Includes a fully sealed helmet and environmental systems." },
        { cat: "Armor", dnd: "Shield", sw: "Energy Shield / Riot Shield", dmg: "+2 AC", props: "Shield", weight: "6 lb", cost: "100 cr", desc: "Wrist-mounted deflector screen or Imperial heavy riot plasteel.", fullDesc: "Can be flavored as a heavy, transparent plasteel riot shield or a high-tech, wrist-mounted emitter that projects a localized energy deflector screen." },
        { cat: "Armor", dnd: "", sw: "Personal Deflector Shield", dmg: "Temp HP", props: "Belt", weight: "2 lb", cost: "5,000 cr", desc: "Energy shield belt granting Temporary Hit Points.", fullDesc: "A specialized, rechargeable shield generator worn on a belt. As a bonus action, activate to gain 10 temporary hit points. Requires a short rest to recharge its power cell." },
        { cat: "Armor", dnd: "Cloak of Protection", sw: "Shadowsilk Cloak", dmg: "+1 AC / +1 Saves", props: "Wondrous Item", weight: "1 lb", cost: "Rare", desc: "A cloak woven from sensor-baffling exotic materials.", fullDesc: "A rare cloak that subtly refracts light and scrambles basic targeting sensors. It grants a +1 bonus to AC and saving throws while worn." },

        { cat: "Gear", dnd: "Potion of Healing", sw: "Bacta Stim", dmg: "2d4+2 HP", props: "Consumable", weight: "0.5 lb", cost: "500 cr", desc: "Injector pen that rapidly accelerates cellular repair.", fullDesc: "A pressurized auto-injector filled with refined Bacta fluid. Using an action to administer the stim rapidly accelerates cellular regeneration, healing 2d4 + 2 HP instantly." },
        { cat: "Gear", dnd: "Healer's Kit", sw: "Medpac", dmg: "Stabilize", props: "10 Uses", weight: "3 lb", cost: "500 cr", desc: "A comprehensive medical kit for field triage.", fullDesc: "Contains bandages, synth-flesh, cauterizers, and minor stimulants. As an action, you can expend one use of the kit to stabilize a creature that has 0 hit points, without needing to make a Wisdom (Medicine) check." },
        { cat: "Gear", dnd: "Thieves' Tools", sw: "Slicer Kit", dmg: "Tool", props: "Tool", weight: "1 lb", cost: "250 cr", desc: "Datapads and security spikes used to bypass blast doors and terminals.", fullDesc: "A specialized kit containing micro-datapads, custom encryption spikes, and localized EMP emitters. Proficiency allows adding your bonus to hack electronic locks or terminals." },
        { cat: "Gear", dnd: "Crowbar", sw: "Fusion Cutter", dmg: "Tool", props: "Tool / Improvised Weapon", weight: "5 lb", cost: "20 cr", desc: "A heavy industrial cutting torch.", fullDesc: "Used to cut through bulkheads and wreckage. Grants advantage on Strength checks where the cutter's intense heat or leverage can be applied." },
        { cat: "Gear", dnd: "Torch", sw: "Glowrod", dmg: "Tool", props: "Equipment", weight: "1 lb", cost: "10 cr", desc: "Provides bright light in a 20-foot radius.", fullDesc: "A standard, battery-operated illumination device. It casts bright light in a 20-foot radius and dim light for an additional 20 feet. Lasts for hundreds of hours on a single charge." },
        { cat: "Gear", dnd: "Caltrops", sw: "Mag-Caltrops", dmg: "Hazard", props: "Equipment", weight: "2 lb", cost: "50 cr", desc: "Magnetic spikes that adhere to boots or droid treads.", fullDesc: "As an action, you can spread a bag of mag-caltrops over a 5-foot-square area. Any creature moving through the area must succeed on a DC 15 Dexterity save or stop moving and take 1 piercing damage." },
        { cat: "Gear", dnd: "Rope, Hempen", sw: "Fibercord Grapple", dmg: "Tool", props: "Equipment", weight: "10 lb", cost: "10 cr", desc: "50 feet of ultra-thin, high-tensile fibercord with a magnetic grapnel.", fullDesc: "A spool containing 50 feet of ultra-thin, incredibly strong synthetic fibercord capped with a magnetic grappling hook." },
        { cat: "Gear", dnd: "Breathing Gear", sw: "Roamer-6 Breath Mask", dmg: "Tool", props: "Equipment", weight: "1 lb", cost: "200 cr", desc: "Filters toxic gases and allows underwater breathing.", fullDesc: "A compact rebreather mask that covers the nose and mouth. It filters out common atmospheric toxins (granting advantage against poison gas) and holds a 2-hour supply of oxygen for aquatic use." },
        { cat: "Gear", dnd: "Rations (1 Day)", sw: "Ration Pack", dmg: "Consumable", props: "Equipment", weight: "2 lb", cost: "5 cr", desc: "High-calorie protein paste and purified water.", fullDesc: "A vacuum-sealed pack of condensed protein cubes, nutritional paste, and a self-heating element. Tastes terrible, but sustains you for one full day." },
        { cat: "Gear", dnd: "Broom of Flying", sw: "Z-6 Jetpack", dmg: "Mobility", props: "Equipment / Fuel", weight: "20 lb", cost: "5,000 cr", desc: "Provides a flying speed of 50 feet.", fullDesc: "A Mandalorian-style or bounty hunter jetpack. As an action, you can activate the thrusters. It provides a flying speed of 50 feet. It carries enough fuel for 1 hour of continuous flight." },
        { cat: "Gear", dnd: "", sw: "Comlink", dmg: "Tool", props: "Equipment", weight: "0.1 lb", cost: "25 cr", desc: "Standard handheld/wrist communication device.", fullDesc: "A standard communications transceiver. Models range from handheld cylinders to wrist-mounted or helmet-integrated arrays. Works seamlessly within planetary range or in orbit." },
        { cat: "Gear", dnd: "Spyglass", sw: "Electrobinoculars", dmg: "Tool", props: "Equipment", weight: "1 lb", cost: "100 cr", desc: "Advanced long-range optics with overlays.", fullDesc: "Handheld optical device. Grants advantage on Wisdom (Perception) checks relying on sight at long range. Includes night-vision, distance readout, and thermal overlays." },
        { cat: "Gear", dnd: "Sending Stones", sw: "Holocomm Projector", dmg: "Communication", props: "Wondrous Item", weight: "0.5 lb", cost: "Rare", desc: "Allows a brief, real-time holographic conversation.", fullDesc: "A paired set of portable holographic projectors. You can use an action to project a real-time, blue-tinted hologram to the paired device, allowing a conversation of up to 5 minutes anywhere in the galaxy." }
    ];

    const classCodeMap = { Sorcerer:"Sor", Wizard:"Wiz", Cleric:"Clr", Druid:"Drd", Bard:"Brd", Paladin:"Pal", Ranger:"Rng", Artificer:"Art", Warlock:"War", Fighter:"Wiz", Rogue:"Wiz", Monk:null };

    function maxSpellLevel(cls, lvl) {
        if (!cls || !lvl) return -1;
        const full = (l) => l>=17?9 : l>=15?8 : l>=13?7 : l>=11?6 : l>=9?5 : l>=7?4 : l>=5?3 : l>=3?2 : 1;
        const half = (l) => l>=17?5 : l>=13?4 : l>=9?3 : l>=5?2 : l>=2?1 : 0;
        const third = (l) => l>=19?4 : l>=13?3 : l>=7?2 : l>=3?1 : 0;
        const warlock = (l) => l>=9?5 : l>=7?4 : l>=5?3 : l>=3?2 : 1;
        switch (cls) {
            case "Sorcerer": case "Wizard": case "Cleric": case "Druid": case "Bard": return full(lvl);
            case "Paladin": case "Ranger": case "Artificer": return Math.max(half(lvl), cls==="Artificer"?(lvl>=2?1:0):0);
            case "Warlock": return warlock(lvl);
            case "Monk": return 0;
            default: return 0;
        }
    }

    const planetData = [
        { name: "Coruscant", x: 50, y: 50, capital: "Galactic City", terrain: "Ecumenopolis", env: "Urban / Cityscape", climate: "Controlled / Temperate", color: "from-amber-900 to-slate-900", desc: "The heart of the galaxy. An ecumenopolis where the entire surface is covered by one massive city.", background: "For millennia, Coruscant has served as the political hub of the galaxy. It is home to the Galactic Senate and the Jedi Temple. Its upper levels are a display of extreme wealth, while the lower levels (down to Level 1313) are hubs of crime and poverty." },
        { name: "Tatooine", x: 80, y: 15, capital: "Bestine", terrain: "Desert", env: "Desert / Wasteland", climate: "Arid / Dual Suns", color: "from-orange-900 to-yellow-900", desc: "A harsh desert world in the Outer Rim, ruled by Hutt cartels and scavengers.", background: "Orbiting twin suns (Tatoo I and II), this world is sparsely populated. Bestine is the administrative capital, though Mos Eisley and Mos Espa are more famous spaceports. It is the homeworld of the Skywalker lineage and the infamous Jawa and Sand People species." },
        { name: "Naboo", x: 60, y: 30, capital: "Theed", terrain: "Plains, Swamps, Oceans", env: "Plains / Swamps / Oceans", climate: "Temperate / Ideal", color: "from-teal-900 to-emerald-950", desc: "A peaceful, lush world known for its high culture, beautiful architecture, and Gungan underwater cities.", background: "Naboo is unique for its hollow core filled with water, allowing Gungans to traverse the planet's interior. The surface is home to the Naboo people, led by a democratically elected monarch. It played a pivotal role in the rise of the Empire." },
        { name: "Alderaan", x: 45, y: 45, capital: "Aldera", terrain: "Mountains, Grasslands", env: "Mountains / Grasslands", climate: "Temperate / Scenic", color: "from-blue-700 to-emerald-900", desc: "The 'bright center of the galaxy,' known for its pacifism and stunning natural beauty. (Post-Imperial status: Debris Field).", background: "A core world with no standing army, Alderaan was a center of arts, culture, and diplomacy. It was a key founding world of the Rebel Alliance, which eventually led to its tragic destruction by the first Death Star as a display of Imperial terror." },
        { name: "Hoth", x: 10, y: 20, capital: "Echo Base (Defunct)", terrain: "Ice, Snow", env: "Glacial / Tundra", climate: "Frozen / Sub-Zero", color: "from-blue-900 to-slate-100/10", desc: "A remote, frozen wasteland in the Anoat sector. Home to the tauntaun and the deadly wampa.", background: "Hoth has no indigenous sentient population and very few visitors. It served as the secret headquarters for the Rebel Alliance until the Imperial discovery and the subsequent Battle of Hoth. Its surface temperatures are lethal without specialized gear." },
        { name: "Mustafar", x: 15, y: 80, capital: "Fralideja", terrain: "Volcanic", env: "Lava / Volcanic", climate: "Extreme / Molten", color: "from-red-900 to-orange-950", desc: "A tiny, volatile planet rich in minerals, dominated by rivers of lava and obsidian mountains.", background: "Mustafar was a stronghold for the Techno Union and later the site of the final duel between Anakin Skywalker and Obi-Wan Kenobi. Darth Vader eventually constructed his personal fortress here, drawing power from the planet's dark side locus." },
        { name: "Kamino", x: 90, y: 90, capital: "Tipoca City", terrain: "Ocean", env: "Global Ocean", climate: "Stormy / Raining", color: "from-cyan-900 to-blue-950", desc: "An aquatic world perpetually covered in storms. Known for the Tipoca City cloning facilities.", background: "Located just outside the Rishi Maze, Kamino is home to the Kaminoans — masters of genetic engineering. They produced the Grand Army of the Republic. The planet is entirely covered by water, with cities built on massive stilts above the crashing waves." },
        { name: "Geonosis", x: 85, y: 10, capital: "Stalgasin Hive", terrain: "Desert, Canyons", env: "Canyons / Spires", climate: "Hot / Arid", color: "from-red-800 to-amber-900", desc: "A rocky, ringed planet inhabited by insectoid Geonosians. Primary site of droid foundries.", background: "The site of the first battle of the Clone Wars. The Geonosians are expert engineers who helped design the Death Star. After the war, the Empire sterilized the planet to keep its construction projects secret." },
        { name: "Bespin", x: 50, y: 70, capital: "Cloud City", terrain: "Gas Giant", env: "Gas Giant / Atmosphere", climate: "Temperate (Sky Level)", color: "from-orange-800 to-pink-900", desc: "A massive gas giant with a thin layer of breathable atmosphere where Tibanna gas is mined.", background: "Bespin is a key source of Tibanna gas, used in blaster weapons and hyperdrives. Cloud City is a major luxury resort and industrial hub suspended in the atmosphere. It was famously governed by Lando Calrissian before being occupied by the Empire." },
        { name: "Endor", x: 30, y: 10, capital: "Bright Tree Village", terrain: "Forests, Mountains", env: "Forest / Jungle", climate: "Temperate / Humid", color: "from-emerald-900 to-green-950", desc: "The 'Forest Moon' orbits a massive gas giant. Home to the Ewoks and giant trees.", background: "Endor is a remote world that became the staging ground for the final battle against the second Death Star. Its dense forests are inhabited by primitive but resourceful Ewoks. The moon's gravity is maintained by the gas giant it orbits." },
        { name: "Kashyyyk", x: 65, y: 55, capital: "Kachirho", terrain: "Jungle / Arboreal", env: "Massive Wroshyr Forests", climate: "Humid / Tropical", color: "from-green-900 to-amber-950", desc: "Homeworld of the Wookiees, dominated by towering forests and diverse wildlife.", background: "Kashyyyk is famous for its wroshyr trees, which can reach several kilometers in height. Wookiees build their cities in the upper canopies. The planet has been the site of numerous battles, particularly during the Clone Wars and the Imperial era." },
        { name: "Mandalore", x: 70, y: 70, capital: "Sundari", terrain: "Waste / Biodomes", env: "Desertified / War-torn", climate: "Hostile / Dry", color: "from-slate-800 to-red-950", desc: "Outer Rim world of legendary warriors, once lush but now devastated by centuries of warfare.", background: "Mandalore's surface was scorched during the Great Clan Wars, forcing its inhabitants into large domed cities like Sundari. It is the spiritual home of the Mandalorian people and their unique culture of honor and combat." },
        { name: "Yavin 4", x: 35, y: 75, capital: "Great Temple (Base)", terrain: "Ancient Jungle", env: "Tropical / Ruins", climate: "Warm / Humid", color: "from-emerald-800 to-yellow-950", desc: "A moon orbiting Yavin Prime, containing ancient temples built by the Massassi.", background: "Yavin 4 served as the primary headquarters for the Rebel Alliance during the Battle of Yavin. The moon is covered in dense jungles and littered with ancient stone temples that resonate with the Force." },
        { name: "Dathomir", x: 80, y: 85, capital: "Nightsister Stronghold", terrain: "Red Forest / Swamp", env: "Dark / Eerie", climate: "Toxic / Unsettling", color: "from-red-950 to-purple-950", desc: "A dark, red-lit planet strong in the dark side of the Force. Home to the Nightsisters.", background: "Dathomir is a world of rugged beauty and deadly mystery. It is ruled by the Nightsisters, a clan of Force-sensitive witches who use dark magics. The planet's atmosphere is tinted red by its sun, giving it a perpetually ominous appearance." },
        { name: "Exegol", x: 5, y: 95, capital: "Sith Citadel", terrain: "Barren / Stormy", env: "Desert / Sith Redoubt", climate: "Deadly / Constant Lightning", color: "from-slate-900 to-blue-950", desc: "A hidden Sith world in the Unknown Regions, serving as a bastion for the Dark Side.", background: "Exegol is a barren, rocky world where the veil between the living and the dead is thin. It was a secret stronghold for the Sith Eternal and the site of the Final Order's fleet construction." },
        { name: "Concord Dawn", x: 75, y: 65, capital: "Concord Dawn City", terrain: "Agricultural Plains, Canyons", env: "Plains / Canyons", climate: "Temperate", color: "from-amber-700 to-green-900", desc: "A world of agricultural plains and rugged canyons, famously the homeworld of Jango Fett.", background: "Concord Dawn is a world in the Mandalore system with a long history of conflict. It is known for its elite warriors, the Journeyman Protectors, and its fractured moon, which was devastated during a cataclysmic war." }
    ];
    
    const spellData = [
        { lvl: "Cantrip", dnd: "Fire Bolt", sw: "Force Combustion", type: "Attack", dmg: "1d10", classes: ["Sor", "Wiz", "Art"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Somatic", desc: "1d10 Fire. Agitate molecules in the air through the Force.", fullDesc: "You channel the Force to hyper-agitate molecules. Make a ranged spell attack. On a hit, 1d10 fire damage. Damage increases at level 5 (2d10), 11 (3d10), and 17 (4d10)." },
        { lvl: "Cantrip", dnd: "Mage Hand", sw: "Force Pull/Push (Minor)", type: "Utility", classes: ["Sor", "Wiz", "Brd", "War"], cast: "1 Action", range: "30 ft", dur: "1 Minute", comp: "Somatic", desc: "Telekinetically manipulate objects up to 30ft away.", fullDesc: "You create an invisible, telekinetic grip. You can use your action to manipulate an object, open a door, or retrieve an item. Max 10 lbs." },
        { lvl: "Cantrip", dnd: "Ray of Frost", sw: "Force Chill / Cryo", type: "Attack", dmg: "1d8", classes: ["Sor", "Wiz", "Art"], cast: "1 Action", range: "60 ft", dur: "Instantaneous", comp: "Somatic", desc: "1d8 Cold, slows movement. Drain thermal energy.", fullDesc: "Make a ranged spell attack. On a hit, 1d8 cold damage, and its speed is reduced by 10 feet. Damage scales at higher levels." },
        { lvl: "Cantrip", dnd: "Vicious Mockery", sw: "Mind Trick (Doubt)", type: "Save", saveStat: "WIS", dmg: "1d4", classes: ["Brd"], cast: "1 Action", range: "60 ft", dur: "Instantaneous", comp: "Verbal", desc: "1d4 Psychic, Disadv. Plant fear in a weak mind.", fullDesc: "Target must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on its next attack roll." },
        { lvl: "Cantrip", dnd: "Eldritch Blast", sw: "Focused Force Push", type: "Attack", dmg: "1d10", classes: ["War"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Somatic", desc: "1d10 Force. Unerring telekinetic blasts.", fullDesc: "Make a ranged spell attack. On a hit, 1d10 force damage. Creates more beams at level 5, 11, and 17." },
        { lvl: "Cantrip", dnd: "Shocking Grasp", sw: "Minor Force Lightning", type: "Attack", dmg: "1d8", classes: ["Sor", "Wiz", "Art"], cast: "1 Action", range: "Touch", dur: "Instantaneous", comp: "Somatic", desc: "1d8 Lightning. Prevents reactions. Short-circuit a droid.", fullDesc: "Melee spell attack. Advantage if target is metal/Droid. On hit, 1d8 lightning damage, and no reactions until next turn." },
        { lvl: "Cantrip", dnd: "Guidance", sw: "Force Premonition", type: "Utility", classes: ["Clr", "Drd", "Art"], cast: "1 Action", range: "Touch", dur: "Concentration, 1 min", comp: "Somatic", desc: "Add 1d4 to a check. Glimpse the immediate future.", fullDesc: "Target rolls a d4 and adds it to one ability check of its choice." },
        { lvl: "Cantrip", dnd: "Sacred Flame", sw: "Force Judgment", type: "Save", saveStat: "DEX", dmg: "1d8", classes: ["Clr"], cast: "1 Action", range: "60 ft", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "1d8 Radiant, ignores cover. Light Side energy.", fullDesc: "Target must succeed on a Dexterity saving throw or take 1d8 radiant damage. No benefit from cover." },
        { lvl: "Cantrip", dnd: "Mending", sw: "Tech Repair", type: "Utility", classes: ["Brd", "Clr", "Drd", "Sor", "Wiz", "Art"], cast: "1 Minute", range: "Touch", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "Restore a single break or tear. Field repair gear.", fullDesc: "Repairs a single break or tear in an object. Max 1 foot dimension." },
        { lvl: "Cantrip", dnd: "Sorcerer's Burst", sw: "Force Surge / Pulse", type: "Attack", dmg: "1d8", classes: ["Sor"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "1d8 variable damage. Explodes on an 8.", fullDesc: "Make a ranged spell attack. On a hit, 1d8 damage of a type you choose (Acid, Cold, Fire, Force, Lightning, Poison, Psychic, or Thunder). If you roll an 8 on the d8, roll an additional d8 and add it to the damage. Damage scales at level 5, 11, and 17." },
        
        { lvl: "1st", dnd: "Magic Missile", sw: "Force Barrage", type: "Auto", dmg: "3d4+3", classes: ["Sor", "Wiz"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Somatic", desc: "3 darts, 1d4+1 Force. Unerring telekinetic strikes.", fullDesc: "Three glowing darts of Force energy. Each hits automatically. 1d4 + 1 force damage each." },
        { lvl: "1st", dnd: "Shield", sw: "Force Barrier / Deflector", type: "Utility", classes: ["Sor", "Wiz", "War"], cast: "1 Reaction", range: "Self", dur: "1 Round", comp: "Somatic", desc: "+5 AC reaction. Localized telekinetic wall.", fullDesc: "Invisible barrier grants +5 AC until start of next turn. Blocks Magic Missile." },
        { lvl: "1st", dnd: "Cure Wounds", sw: "Force Heal", type: "Utility", dmg: "2d8", classes: ["Brd", "Clr", "Drd", "Pal", "Rng", "Art"], cast: "1 Action", range: "Touch", dur: "Instantaneous", comp: "Somatic", desc: "2d8 + Mod Healing. Channel the living Force to knit flesh.", fullDesc: "Target regains 2d8 + your spellcasting ability modifier HP. (2024 Update: Healing increased from 1d8 to 2d8)." },
        { lvl: "1st", dnd: "Healing Word", sw: "Force Revitalize", type: "Utility", dmg: "2d4", classes: ["Brd", "Clr", "Drd"], cast: "1 Bonus Action", range: "60 ft", dur: "Instantaneous", comp: "Verbal", desc: "2d4 + Mod. Rapid Force surge.", fullDesc: "Target regains 2d4 + your spellcasting ability modifier HP. (2024 Update: Healing increased from 1d4 to 2d4)." },
        { lvl: "1st", dnd: "Thunderwave", sw: "Force Repulse", type: "Save", saveStat: "CON", dmg: "2d8", classes: ["Brd", "Drd", "Sor", "Wiz"], cast: "1 Action", range: "Self (15ft cube)", dur: "Instantaneous", comp: "Somatic", desc: "2d8 Thunder. 15ft cube. Violent outward burst.", fullDesc: "15-foot cube. Constitution saving throw. Fail: 2d8 thunder damage and pushed 10 feet. Success: Half damage, no push." },
        { lvl: "1st", dnd: "Charm Person", sw: "Jedi Mind Trick", type: "Save", saveStat: "WIS", classes: ["Brd", "Drd", "Sor", "Wiz", "War"], cast: "1 Action", range: "30 ft", dur: "1 Hour", comp: "Somatic, Verbal", desc: "Wis save. Target treats you as friendly.", fullDesc: "Wisdom saving throw. Advantage if you are fighting it. If it fails, it is charmed until spell ends." },
        { lvl: "1st", dnd: "Hunter's Mark", sw: "Bounty Tracker HUD", type: "Utility", dmg: "1d6", classes: ["Rng"], cast: "1 Bonus Action", range: "90 ft", dur: "Concentration, 1 hr", comp: "None", desc: "Bonus Action. Deal extra 1d6 damage to target.", fullDesc: "Lock onto target. Deal extra 1d6 damage when you hit with weapon. (2024 Update: No longer grants advantage on tracking, but base damage remains)." },
        { lvl: "1st", dnd: "Command", sw: "Dominate Mind", type: "Save", saveStat: "WIS", classes: ["Clr", "Pal", "Brd", "War"], cast: "1 Action", range: "60 ft", dur: "1 Round", comp: "Verbal", desc: "One-word command they must obey.", fullDesc: "Wisdom saving throw or follow the command on its next turn." },
        { lvl: "1st", dnd: "Bless", sw: "Battle Meditation (Minor)", type: "Utility", classes: ["Clr", "Pal"], cast: "1 Action", range: "30 ft", dur: "Concentration, up to 1 minute", comp: "Verbal, Somatic", desc: "+1d4 to attacks/saves for 3 allies.", fullDesc: "Up to three creatures add 1d4 to attack rolls and saving throws." },
        { lvl: "1st", dnd: "Burning Hands", sw: "Flamethrower Burst", type: "Save", saveStat: "DEX", dmg: "3d6", classes: ["Sor", "Wiz"], cast: "1 Action", range: "Self (15ft cone)", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "3d6 Fire. 15 ft cone. Wrist-mounted flame projector.", fullDesc: "Dexterity saving throw. 3d6 fire damage on fail, half on success." },
        { lvl: "1st", dnd: "Guiding Bolt", sw: "Force Flare", type: "Attack", dmg: "4d6", classes: ["Clr"], cast: "1 Action", range: "120 ft", dur: "1 Round", comp: "Somatic, Verbal", desc: "4d6 Radiant. Next attack has Advantage.", fullDesc: "Make a ranged spell attack. On hit, 4d6 radiant damage. The next attack roll against this target has advantage." },
        { lvl: "1st", dnd: "Inflict Wounds", sw: "Force Rend", type: "Attack", dmg: "3d10", classes: ["Clr"], cast: "1 Action", range: "Touch", dur: "Instantaneous", comp: "Somatic", desc: "3d10 Necrotic. Telekinetically tear tissue.", fullDesc: "Make a melee spell attack. On hit, 3d10 necrotic damage. (2024 Update: Damage increased to 3d10)." },
        { lvl: "1st", dnd: "Chaos Bolt", sw: "Unstable Force Bolt", type: "Attack", classes: ["Sor"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Somatic, Verbal", desc: "2d8+1d6 variable damage. Can leap.", fullDesc: "Make a ranged spell attack. Choose damage type (Acid, Cold, Fire, Force, Lightning, Poison, Psychic, or Thunder). If you roll the same number on both d8s, the bolt leaps to another target." },
        { lvl: "1st", dnd: "Entangle", sw: "Force Bind (Root)", type: "Save", saveStat: "STR", classes: ["Drd"], cast: "1 Action", range: "90 ft", dur: "Concentration, 1 min", comp: "Somatic", desc: "Str save. Restrain targets in 20ft square.", fullDesc: "Force roots sprout from the ground. Strength saving throw or be restrained." },
        
        { lvl: "2nd", dnd: "Hold Person", sw: "Force Stasis / Choke", type: "Save", saveStat: "WIS", classes: ["Brd", "Clr", "Drd", "Sor", "Wiz", "War"], cast: "1 Action", range: "60 ft", dur: "Concentration, 1 min", comp: "Somatic", desc: "Wis save. Paralyzes humanoid. Invisible Force grip.", fullDesc: "Wisdom saving throw or be paralyzed. Repeat save at end of each turn." },
        { lvl: "2nd", dnd: "Invisibility", sw: "Force Cloak / Stealth Field", type: "Utility", classes: ["Brd", "Sor", "Wiz", "Art", "War"], cast: "1 Action", range: "Touch", dur: "Concentration, 1 hr", comp: "Somatic", desc: "Target becomes invisible. Cloud minds.", fullDesc: "Invisible until it attacks or casts a spell." },
        { lvl: "2nd", dnd: "Scorching Ray", sw: "Force Rend / Flamethrower", type: "Attack", classes: ["Sor", "Wiz"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Somatic", desc: "3 rays, 2d6 Fire each. Telekinetically tear targets.", fullDesc: "Three rays. Ranged spell attack for each. 2d6 fire damage each. (2024 Update: Damage scales by +2 rays for higher slots)." },
        { lvl: "2nd", dnd: "Shatter", sw: "Force Crush / Thermal Imploder", type: "Save", saveStat: "CON", classes: ["Brd", "Sor", "Wiz", "War"], cast: "1 Action", range: "60 ft", dur: "Instantaneous", comp: "Somatic", desc: "3d8 Thunder. 10ft radius. Crippling localized crush.", fullDesc: "Constitution saving throw. 3d8 thunder damage on fail, half on success." },
        { lvl: "2nd", dnd: "Misty Step", sw: "Force Dash", type: "Utility", classes: ["Sor", "Wiz", "War"], cast: "1 Bonus Action", range: "Self", dur: "Instantaneous", comp: "Somatic", desc: "Bonus action teleport 30ft.", fullDesc: "Teleport 30 feet to an unoccupied space you can see." },
        { lvl: "2nd", dnd: "Spiritual Weapon", sw: "Telekinetic Lightsaber", type: "Attack", classes: ["Clr"], cast: "1 Bonus Action", range: "60 ft", dur: "1 Minute", comp: "Somatic", desc: "Bonus action. 1d8+Mod Force. Floating saber.", fullDesc: "Bonus action melee spell attack. 1d8 + mod force damage. (2024 Update: Now requires Concentration)." },
        { lvl: "2nd", dnd: "Blur", sw: "Force Speed Cloud", type: "Utility", classes: ["Sor", "Wiz", "Art"], cast: "1 Action", range: "Self", dur: "Concentration, 1 min", comp: "Verbal", desc: "Disadvantage on attacks vs you.", fullDesc: "Attacks against you have disadvantage if the attacker relies on sight." },
        { lvl: "2nd", dnd: "Heat Metal", sw: "Armor Overheat", type: "Save", saveStat: "CON", classes: ["Brd", "Drd", "Art"], cast: "1 Action", range: "60 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "2d8 Fire/turn. Force-heat plasteel.", fullDesc: "Target metal object. 2d8 fire damage if held/worn. Con save vs disadvantage." },
        { lvl: "2nd", dnd: "", sw: "Sith Alchemy / Drain", type: "Save", saveStat: "CON", classes: ["Sor", "Wiz", "War"], cast: "1 Action", range: "30 ft", dur: "Instantaneous", comp: "Somatic", desc: "Drain life force to heal yourself.", fullDesc: "Constitution saving throw. Fail: 3d6 necrotic damage, heal for half. Success: Half damage, no heal." },
        { lvl: "2nd", dnd: "Mirror Image", sw: "Force Illusions", type: "Utility", classes: ["Brd", "Sor", "Wiz", "War"], cast: "1 Action", range: "Self", dur: "1 Minute", comp: "Somatic", desc: "3 duplicates. Harder to hit.", fullDesc: "Create three illusory duplicates. When attacked, roll to see if they hit an image instead. (2024 Update: Images now increase your AC by 1 + your spellcasting mod)." },
        { lvl: "2nd", dnd: "Spike Growth", sw: "Razor Force Shards", type: "Utility", classes: ["Drd", "Rng"], cast: "1 Action", range: "150 ft", dur: "Concentration, 10 min", comp: "Somatic", desc: "20ft radius. 2d4 damage per 5ft moved.", fullDesc: "Area becomes difficult terrain. When a creature moves into or within the area, it takes 2d4 piercing damage for every 5 feet it travels." },
        
        { lvl: "3rd", dnd: "Fireball", sw: "Force Storm / Heavy Detonator", type: "Save", saveStat: "DEX", classes: ["Sor", "Wiz"], cast: "1 Action", range: "150 ft", dur: "Instantaneous", comp: "Somatic", desc: "8d6 Fire. 20ft radius. Massive devastation.", fullDesc: "20-foot-radius sphere. Dexterity saving throw. 8d6 fire damage on fail, half on success." },
        { lvl: "3rd", dnd: "Fly", sw: "Force Levitation / Jetpack", type: "Utility", classes: ["Sor", "Wiz", "Art", "War"], cast: "1 Action", range: "Touch", dur: "Concentration, 10 min", comp: "Somatic", desc: "60ft fly speed. Defy gravity.", fullDesc: "Target gains 60 feet flying speed for the duration." },
        { lvl: "3rd", dnd: "Haste", sw: "Battle Meditation / Speed", type: "Utility", classes: ["Sor", "Wiz", "Art"], cast: "1 Action", range: "30 ft", dur: "Concentration, 1 min", comp: "Somatic", desc: "Doubles speed, +2 AC, extra action.", fullDesc: "Speed doubled, +2 AC, extra action (Attack, Dash, Disengage, Hide, Use Object)." },
        { lvl: "3rd", dnd: "Counterspell", sw: "Force Absorb / Deflection", type: "Save", saveStat: "CON", classes: ["Sor", "Wiz", "War"], cast: "1 Reaction", range: "60 ft", dur: "Instantaneous", comp: "Somatic", desc: "Reaction. Interrupt cast.", fullDesc: "(2024 Update: Target makes a Constitution saving throw. On a failure, the spell fails and the slot is expended)." },
        { lvl: "3rd", dnd: "Lightning Bolt", sw: "Sith Lightning", type: "Save", saveStat: "DEX", classes: ["Sor", "Wiz"], cast: "1 Action", range: "Self (100ft line)", dur: "Instantaneous", comp: "Somatic", desc: "8d6 Lightning. 100ft line.", fullDesc: "100-foot-long, 5-foot-wide line. Dexterity saving throw. 8d6 lightning damage on fail, half on success." },
        { lvl: "3rd", dnd: "Dispel Magic", sw: "Force Sever / Slice Override", type: "Utility", classes: ["Brd", "Clr", "Drd", "Pal", "Sor", "Wiz", "War", "Art"], cast: "1 Action", range: "120 ft", dur: "Instantaneous", comp: "Somatic", desc: "End ongoing effects.", fullDesc: "End spells of 3rd level or lower on target. (2024 Update: Now always works on 3rd level or lower, no check needed)." },
        { lvl: "3rd", dnd: "Revivify", sw: "Bacta Tank Field Module", type: "Utility", classes: ["Clr", "Pal", "Rng", "Art"], cast: "1 Action", range: "Touch", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "Return creature dead ≤1 min to 1 HP.", fullDesc: "Return dead creature to 1 HP. Does not work on Droids/Undead." },
        { lvl: "3rd", dnd: "Slow", sw: "Force Drag", type: "Save", saveStat: "WIS", classes: ["Sor", "Wiz"], cast: "1 Action", range: "120 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "6 creatures, halved speed and one action.", fullDesc: "Wisdom saving throw. Affected targets have halved speed, -2 AC/Dex saves, no reactions, one action only." },
        { lvl: "3rd", dnd: "Beacon of Hope", sw: "Force Bastion", type: "Utility", classes: ["Clr"], cast: "1 Action", range: "30 ft", dur: "Concentration, 1 min", comp: "Somatic, Verbal", desc: "Adv on Wis/Death saves. Max healing.", fullDesc: "Targets have advantage on Wisdom saving throws and death saving throws, and regain the maximum number of hit points possible from any healing." },
        
        { lvl: "4th", dnd: "Wall of Fire", sw: "Plasma Barrier", type: "Save", saveStat: "DEX", classes: ["Drd", "Sor", "Wiz"], cast: "1 Action", range: "120 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "5d8 Fire. 60 ft wall. Plasma emitter.", fullDesc: "Dexterity saving throw when wall appears. 5d8 fire damage on fail, half on success." },
        { lvl: "4th", dnd: "Polymorph", sw: "Beast Bond Transformation", type: "Save", saveStat: "WIS", classes: ["Brd", "Drd", "Sor", "Wiz"], cast: "1 Action", range: "60 ft", dur: "Concentration, 1 hr", comp: "Verbal, Somatic", desc: "Transform target into beast.", fullDesc: "Wisdom saving throw (willing targets can fail). Transform into a beast of CR equal or lower than target level." },
        { lvl: "4th", dnd: "Greater Invisibility", sw: "Phase-Shift Cloak", type: "Utility", classes: ["Brd", "Sor", "Wiz"], cast: "1 Action", range: "Touch", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "Invisible while attacking.", fullDesc: "Target remains invisible even when attacking or casting spells." },
        { lvl: "4th", dnd: "Banishment", sw: "Force Exile", type: "Save", saveStat: "CHA", classes: ["Clr", "Pal", "Sor", "Wiz", "War"], cast: "1 Action", range: "60 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "Send target to another plane.", fullDesc: "Charisma saving throw. Fail: Banished to a harmless demiplane (or home plane) for the duration." },
        { lvl: "4th", dnd: "Dimension Door", sw: "Force Phase", type: "Utility", classes: ["Brd", "Sor", "Wiz", "War"], cast: "1 Action", range: "500 ft", dur: "Instantaneous", comp: "Verbal", desc: "Teleport 500 ft + 1 ally.", fullDesc: "Teleport yourself and one willing creature up to 500 feet." },
        { lvl: "4th", dnd: "Guardian of Faith", sw: "Force Sentinel", type: "Auto", classes: ["Clr"], cast: "1 Action", range: "30 ft", dur: "8 Hours", comp: "Verbal", desc: "Spectral guardian deals 20 Force damage.", fullDesc: "A large spectral guardian appears. Any creature hostile to you that moves to a space within 10 feet of the guardian for the first time on a turn or starts its turn there must succeed on a Dexterity saving throw or take 20 radiant damage." },
        
        { lvl: "5th", dnd: "Cone of Cold", sw: "Cryo-Detonator Wave", type: "Save", saveStat: "CON", classes: ["Sor", "Wiz"], cast: "1 Action", range: "Self (60ft cone)", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "8d8 Cold. 60 ft cone. Mass thermal drain.", fullDesc: "Constitution saving throw. 8d8 cold damage on fail, half on success." },
        { lvl: "5th", dnd: "Hold Monster", sw: "Force Stasis (Greater)", type: "Save", saveStat: "WIS", classes: ["Brd", "Sor", "Wiz", "War"], cast: "1 Action", range: "90 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "Paralyze any creature. Frozen-in-place.", fullDesc: "Wisdom saving throw or be paralyzed. Repeat save at end of each turn." },
        { lvl: "5th", dnd: "Telekinesis", sw: "Force Lift / Crush", type: "Utility", classes: ["Sor", "Wiz"], cast: "1 Action", range: "60 ft", dur: "Concentration, 10 min", comp: "Verbal, Somatic", desc: "Move creatures/objects up to 1000 lbs.", fullDesc: "Contested ability check (Casting Stat vs target Str) to move/restrain. Move objects up to 1000 lbs." },
        { lvl: "5th", dnd: "Mass Cure Wounds", sw: "Battlefield Bacta Burst", type: "Utility", classes: ["Brd", "Clr", "Drd"], cast: "1 Action", range: "60 ft", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "5d8+Mod healing to 6 creatures.", fullDesc: "Up to six creatures regain 5d8 + casting mod HP. (2024 Update: Healing increased from 3d8 to 5d8)." },
        { lvl: "5th", dnd: "Dominate Person", sw: "Mind Control (Major)", type: "Save", saveStat: "WIS", classes: ["Brd", "Sor", "Wiz", "War"], cast: "1 Action", range: "60 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "Take complete control of a humanoid.", fullDesc: "Wisdom saving throw. Advantage if you are fighting it. On failure, you control its actions via telepathic link." },
        { lvl: "5th", dnd: "Flame Strike", sw: "Force Nova", type: "Save", saveStat: "DEX", classes: ["Clr"], cast: "1 Action", range: "60 ft", dur: "Instantaneous", comp: "Verbal, Somatic", desc: "8d6 Fire/Radiant. 10ft cylinder.", fullDesc: "A vertical column of Force energy roars down. 8d6 damage (half fire, half radiant). Dexterity save for half." },
        { lvl: "5th", dnd: "Cloudkill", sw: "Toxic Force Cloud", type: "Save", saveStat: "CON", classes: ["Sor", "Wiz"], cast: "1 Action", range: "120 ft", dur: "Concentration, 10 min", comp: "Verbal, Somatic", desc: "5d8 Poison. 20ft radius moving cloud.", fullDesc: "Creates a 20-foot-radius sphere of poisonous, yellow-green fog. 5d8 poison damage. The fog moves 10 feet away from you each turn." },
        { lvl: "5th", dnd: "Animate Objects", sw: "Telekinetic Swarm", type: "Utility", classes: ["Brd", "Sor", "Wiz"], cast: "1 Action", range: "120 ft", dur: "Concentration, 1 min", comp: "Verbal, Somatic", desc: "Animate up to 10 objects. Swarm enemies.", fullDesc: "You telekinetically animate up to 10 non-magical objects. They become creatures under your control. (2024 Update: Now simplified into a 'Swarm' stat block)." }
    ];
